blog/urls.py
from django.urls import path,register_converter
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import ListView
from .views import BuyCarListView,BuyCarDetailView, SellCarCreateView,TakeRentListView,TakeRentDetailView,ChooseCarListView,ChooseCarDetailView

app_name = 'blog'
urlpatterns = [
    path('', views.home_page,name='home_page'),
    path('contact/',views.contact,name='contact' ),
    path('rent/',views.rent,name='rent' ),
    path('giverent/',views.giverent,name='giverent' ),
    #path('takerent/',views.takerent,name='takerent' ),
    path('selfdriven/',views.selfdriven,name='selfdriven' ),
    # path('sell-car/',views.sellcar,name='sellcar' ),

    path('sell-car/',SellCarCreateView.as_view(),name='sellcar' ),
    path('takerent/',TakeRentListView.as_view(),name='takerent' ),
    path('choose_car/',ChooseCarListView.as_view(),name='choose_car' ),
    path('choose_car/<int:pk>',ChooseCarDetailView.as_view(),name='detail1' ),
    path('takerent/<int:pk>',TakeRentDetailView.as_view(),name='detail1' ),
    # path('post/<int:pk>/update/',PostUpdateView.as_view(),name='update' ),
    path('buy-car/',BuyCarListView.as_view(),name='buycar' ),
    path('post/<int:pk>/',BuyCarDetailView.as_view(),name='detail' ),
    path('user_form_car/',views.User_f,name='User_f' ),
]

car_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('user/', include('users.urls')),

]

if(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'
urlpatterns = [
    path('registration/',views.registration,name='registration'),
    path('profile/',views.profile,name='profile'),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
]

blog/models.py
from django.db import models
from users.models import User_profile
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
class Contact(models.Model):

    name = models.CharField(max_length=50,blank=False)
    email = models.EmailField(blank=False)
    message = models.TextField()

    def __str__(self):

        return self.name

class Giverent_field(models.Model):

    car_name = models.CharField(max_length=50)
    car_type = models.CharField(max_length=20)
    image = models.ImageField(upload_to='media/images')
    seat_capacity = models.IntegerField()
    contact_number = models.IntegerField()
    location = models.CharField(max_length=250)

class car_choose(models.Model):
    car_name = models.CharField(max_length=50)
    contact = models.CharField(max_length=20)
    client = models.CharField(max_length=20)
    description = models.TextField(max_length=400)
    image = models.ImageField(upload_to='media/car_profile')

class sell_car_post(models.Model):

    author = models.ForeignKey(User,on_delete=models.CASCADE)
    car_name = models.CharField(max_length=100)
    engine_capacity = models.CharField(max_length=20)
    model = models.CharField(max_length=20)
    color = models.CharField(max_length=20)
    seat_capacity = models.CharField(max_length=20)
    price = models.CharField(max_length=20)
    image = models.ImageField(default='default.jpg',upload_to='pictures/')

    def get_absolute_url(self):
        return reverse('blog:buycar')
class User_rent_form(models.Model):

    fname = models.CharField(max_length=50)
    lname = models.CharField(max_length=50)
    phone = models.PositiveIntegerField()
    rent_date = models.DateField()
    duration = models.CharField(max_length=50)
    upload_lic = models.ImageField(upload_to='media/license')

blog/forms.py
from django import forms
from .models import Contact, Giverent_field, sell_car_post
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column,Field

class Contact_form(forms.ModelForm):

    class Meta:
        model = Contact
        fields = '__all__'    #['name','email','message']
        #widgets = {
        #     'email' : forms.TextInput(attrs={'placeholder':'Email','required':True}),
        #     'name' : forms.TextInput(attrs={'placeholder':'Full-Name','required':True}),
         #    'message' : forms.Textarea(
         #                    attrs={'required':True,
         #                           'rows': 200,
         #                           'cols':50,
         #                           'style':'resize:none;',
         #                          'placeholder':'message'
         #            })
         # }

    # helper = FormHelper()
    # helper.form_method = 'POST'
    # helper.add_input(Submit('Submit','Submit', css_class='btn-primary pos'))
    # helper.layout = Layout(
    #     Column('name',css_id="form-group1",placeholder="Name"),
    #     Column('email',css_class='',placeholder="Email"),
    #     Column('message',css_class='',placeholder="Message")
    # )
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Column('name',css_class='form-group col-md-12 mb-0'),
            Column('email',css_class='form-group col-md-12 mb-0'),
            Column('message',css_class='form-group col-md-12 mb-0'),
            Submit('submit', 'Submit',css_class="btn-success pos")
        )
        self.fields['name'].label = "Name :"
        self.fields['email'].label = "Email :"
        self.fields['message'].label = "Message :"
        self.fields['message'].widget.attrs['style'] = 'resize:none'
        self.fields['name'].widget.attrs['placeholder'] = 'Full-Name'
        self.fields['email'].widget.attrs['placeholder'] = 'Email'
        self.fields['message'].widget.attrs['placeholder'] = 'Message'

class Giverent_form(forms.ModelForm):

    class Meta:
        model = Giverent_field
        fields = ['car_name','car_type','image','seat_capacity','contact_number','location']


    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Column('car_name',css_class='form-group col-md-12 mb-0'),
            Column('car_type',css_class='form-group col-md-12 mb-0'),
            Column('image',css_class='form-group col-md-12 mb-0'),
            Column('seat_capacity',css_class='form-group col-md-12 mb-0'),
            Column('contact_number',css_class='form-group col-md-12 mb-0'),
            Column('location',css_class='form-group col-md-12 mb-0'),
            Submit('submit', 'Submit',css_class="btn-success pos")
        )
        self.fields['car_name'].label = "Car Name :"
        self.fields['car_type'].label = "car type :"
        self.fields['image'].label = "image :"
        self.fields['seat_capacity'].label = "Seat capacity :"
        self.fields['contact_number'].label = "Contact number :"
        self.fields['location'].label = "location :"


# class form_post(forms.ModelForm):
#
#     class Meta:
#         model = sell_car_post
#         fields = ['car_name','registration_date','car_detail']
#
#     def __init__(self,*args,**kwargs):
#         super().__init__(*args,**kwargs)
#         self.helper = FormHelper()
#         self.helper.layout = Layout(
#             Column('car_name',css_class='form-group col-md-12 mb-0'),
#             Column('registration_date',css_class='form-group col-md-12 mb-0'),
#             Column('car_detail',css_class='form-group col-md-12 mb-0'),
#             Submit('submit', 'Post',css_class="btn btn-success pos1")
#         )
#         self.fields['car_name'].label = "Car Name :"
#         self.fields['registration_date'].label = "Registration Date :"
#         self.fields['car_detail'].label = "Details of Car :"
#         self.fields['car_detail'].widget.attrs['style'] = 'resize:none'

blog/views.py
from django.shortcuts import render
from .forms import Contact_form,Giverent_form               #form_post
from .models import sell_car_post,Giverent_field,car_choose,User_rent_form
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView, CreateView #UpdateView
from users.models import User_profile
from django.contrib import messages
# Create your views here.
def home_page(request):

    return render(request,'blog/index.html')

def contact(request):

    if(request.method=='POST'):
        form = Contact_form(request.POST or None)
        if(form.is_valid()):
            form.save()
            form = Contact_form()
            messages.success(request,'succesfully posted !')
    else:
        form = Contact_form()
    return render(request,'blog/contact.html',{'form':form})

def rent(request):

    return render(request,'blog/rent.html')

def selfdriven(request):

    return render(request,'blog/selfdriven.html')

# def takerent(request):
#
#     return render(request,'blog/takerent_list.html')

def giverent(request):

    if(request.method=='POST'):
        form = Giverent_form(request.POST , request.FILES)
        if(form.is_valid()):
            form.save()
            form = Giverent_form()
            messages.success(request,'succesfully posted !')
    else:
        form = Giverent_form()
    return render(request,'blog/giverent.html',{'form':form})
# @login_require
# def sellcar(request):
#
#     if(request.method == "POST"):
#         form = form_post(request.POST or None)
#         if(form.is_valid()):
#             form.save()
#             form = form_post()
#
#     else:
#         form = form_post()
#
#     # value = sell_car_post.objects.all()
#
#     return render(request,'blog/sellcar.html',{'form':form})




# def sellcar_post(request):
#
#     value = sell_car_post.objects.all()
#
#     context = {
#         'data': value
#     }
#     return render(request,'blog/buycar.html',context)

class BuyCarListView(ListView):

    model = sell_car_post
    template_name = 'blog/buycar_list.html'
    context_object_name = 'post'

    # def get_context_data(self,**kwargs):
    #     context = super(BuyCarListView,self).get_context_data(**kwargs)
    #     context['post'] = sell_car_post.objects.all()
    #     return context

class TakeRentListView(ListView):

    model = Giverent_field
    template_name = 'blog/takerent_list.html'
    context_object_name = 'post'


class TakeRentDetailView(DetailView):
    model = Giverent_field

class ChooseCarListView(ListView):
    model = car_choose
    template_name = 'blog/choose_car_list.html'
    context_object_name = 'post'

class ChooseCarDetailView(DetailView):
    model = Giverent_field

class BuyCarDetailView(DetailView):
    model = sell_car_post
    # fields = ['image']

class SellCarCreateView(LoginRequiredMixin,CreateView):
    model = sell_car_post
    fields = ['car_name','engine_capacity','model','color','seat_capacity','price','image']

    def form_valid(self,form):
        form.instance.author = self.request.user
        return super().form_valid(form)
def User_f(request):
    post = User_rent_form(request.POST , request.FILES)
    if(request.method=='POST' and request.method=='FILES'):

        fname = request.Post.get('fname')
        lname = request.Post.get('lname')
        phone = request.Post.get('phone')
        rent_date = request.Post.get('rent_date')
        duration = request.Post.get('duration')
        upload_lic = request.FILES.get('upload_lic')
        messages.success(request,'succesfully posted !')

        post = User_rent_form(fname=fname,lname=lname,phone=phone,rent_date=rent_date,duration=duration,upload_lic=upload_lic)
        post.save()          
        
        return render(request,'blog/reg_form.html',{post:post})
    return render(request,'blog/reg_form.html')

blog/templates/blog/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Carmania</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/style.css' %}">

  </head>
  <body style="overflow-x:hidden;">
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mx-auto">
        <a class="navbar-brand" href="#" id="logoimg"><img src="{% static 'blog/images/carlogo.jpg' %}" height="100px"
          width="100px"></a>
      <li class="nav-item active">
        <a class="nav-link color1" href="{% url 'blog:home_page' %}">Home</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link color2" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Service
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'blog:buycar' %}">Buy Car</a>
          <a class="dropdown-item" href="{% url 'blog:sellcar' %}">Sell Car</a>
          <a class="dropdown-item" href="{% url 'blog:rent' %}">Rent Car</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link color3" href="{% url 'blog:contact' %}">Contact</a>
      </li>
      {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link color4" href="{% url 'users:profile' %}">Welcome : {{ user.username }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link color4" href="{% url 'users:logout' %}">Logout</a>
          </li>
      {% else %}
          <li class="nav-item">
            <a class="nav-link color4" href="{% url 'users:login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link color4" href="{% url 'users:registration' %}">Register</a>
          </li>
      {% endif %}
    </ul>
  </div>
</nav>
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}
  {% block body %}
  {% endblock %}



    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

blog/templates/blog/buycar_list.html
{% extends 'blog/base.html' %}
{% load staticfiles %}


{% block body %}

<style>

.jumbotron{
		background: url(../static/blog/images/gold.jpg);
		background-size: cover;
		margin-bottom: auto;
		height: 1500px;
		background-attachment: fixed;
		color: white;
		align-items: center;
	}


.content-table{

border-collapse: separate;
margin: 30px 150px 10px;
font-size: 20px;
width: 58%;

}
.content-table thead tr{

 color: cadetblue;
 text-align: left;
 border-spacing: 30px;
}




</style>
<div class="jumbotron">
  <h1 style="text-align:center; margin-top: -20px">Available Cars</h1>
  
<!-- <img style="border-radius: 50%;width:60px;height:60px;" src="{{ user.user_profile.image.url }}"> -->

<table class="content-table">
  <thead>
    <th style="font-size: larger; color: blue ">Pictures</th>
    <th style="font-size: larger; color:blue " >Choose Your Car</th>
</thead>




{% for value1 in post %}
        <tr>
           <!---- <h1 style="margin-left:10px;">{{ value1.author }}</h1> -->
            <td><img style="width:300px; height:200px;" src="{{ value1.image.url }}"></td>
            <td style="list-style-type: none;">
            <li style="color: white; font-weight: bolder;font-size: larger" >Car Name : <a href="{% url 'blog:detail' pk=value1.pk %}">{{ value1.car_name }}</a></li>
            </tr>
        {% endfor %}
        </table>
        <!-- {% for value1 in image %}
            <img style="border-radius: 50%;width:60px;height:60px;" src="{{ value1.image.url }}">
        {% endfor %} -->

</div>

{% endblock %}

blog/templates/blog/choose_car_list.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block body %}

  <style>

body{
      background-image: url(../static/blog/images/audi.jpg);
      background-size: cover;
    }

        .content-table{

          border-collapse: separate;
           margin-left: 40px;
           font-size: 20px;
           width: 100%;

        }

        .content-table thead tr{

                   color: cadetblue;
                   text-align: left;
        }

  </style>

<body>
<h1 style="text-align: center; margin-top:20px; color: white">Choose your desire car</h1>

<table class="content-table">
  <thead>
    <th>Pictures</th>
    <th>Info</th>

</thead>
  {% for value3 in post %}
  <tr>
    <td><img style="width:300px;height:200px;" src="{{ value3.image.url }}"></td>
    <td style="list-style-type: none;"><li style="color: white" >Car Name : {{ value3.car_name }}</li>
         <li style="color: white" >Contact Number : {{ value3.contact }}</li>
         <li style="color: white" >Client Name : {{ value3.client }}</li>
       <li style="color: white" >Description : {{ value3.description }}</td></li>
       <td style="color:white;"><a href="{% url 'blog:User_f' %}"><input class="btn btn-success" type="submit" name="" value="Book Now"></a></td>

  </tr>
  {% endfor %}
</table>

</body>
{% endblock %}

blog/templates/blog/contact.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block body %}
<body class="body">
  <div class="form_d">
    {% crispy form %}
  </div>
  </body>
{% endblock %}

blog/templates/blog/giverent.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block body %}
<body class="body2">
  <div class="form_d2">
    <div class="container"><h1 class="car">Rent A Car</h1></div>
    <form method="POST" enctype="multipart/form-data" > {% csrf_token %} 
      {{form.as_p}}
        
    <button style="margin-left: 10px" type="submit" class="btn btn-primary">Upload File</button>
  </form>
   
  </div>
  </body>
{% endblock %}

blog/templates/blog/giverent_field_detail.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block body %}
<div class="jumbotron">

    <hr>
    <p>Car Name : {{ object.car_name }}</a></p>
    <p><img style="width:300px;height:200px;" src="{{ object.image.url }}"></p>
    <p>Car Type : {{ object.car_type }}</p>
    <p>Seat Capacity : {{ object.seat_capacity }}</p>
    <p>Contact Number : {{ object.contact_number }}</p>
    <p>Location : {{ object.location }}</p>

</div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block body %}
<body>
  <div class="div1">
    <img class="img" src="{% static 'blog/images/bmw.jpg' %}" alt="">
  <div class="div2">
    <h1 class="h1_design">BUY . SELL . RENT</h1>
  </div>
  <div class="div3">
    <h2 class="p1_design">Want to Explore The Car World </h2>
  </div>
  
  </div>
  
</body>
  

{% endblock %}

blog/templates/blog/rent.html
{% extends 'blog/base.html' %}
{% block body %}

<div class="functions">
  <div class="container2">
    <div class="box_border">
      <div class="boxes">
        <div class="box1"></div>
  <!-- <input type="submit" name="Give Rent"> -->
        <div class="box2"></div>
  <!-- <input type="submit" name="Give Rent"> -->
        <div class="box3"></div>
  <!-- <input type="submit" name="Give Rent"> -->
      </div>
      <div class="button_box">
        <a href="{% url 'blog:giverent' %}"><input type="submit" value="Give rent"></a>
        <a href="{% url 'blog:takerent' %}"><input type="submit" value="Take rent"></a>
        <a href="{% url 'blog:selfdriven' %}"><input type="submit" value="Self drive"></a>
    </div>
    </div>
    
  </div>
</div>
{% endblock %}

blog/templates/blog/selfdriven.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block body %}
<head>
    <style>
        .ptext{
            margin-left:0px;
            margin-right: auto;
            width: 60% ;
            text-align:left;
        }
        .heading{
            padding-left: 50px;
        }
        .main_content{
          display: flex;
          padding-left: 50px;
        }
        
        .side_image{
          margin-right: 100px;
          
        }
        
    </style>
   
</head> 
<section class="container1">

<div class="row custom">
  <div class="heading">
    <h1 class="car1">Self
    <span style="color:blue"> Drive Car Rental </span>
    <span><a style="height: 10px;" class="btn1" href="{% url 'blog:choose_car' %}">CHECK OUR CARS</a></span>
    </h1>
  </div>
    
</div>
<div class="main_content">
  <div class="page-text">
       <p><strong style="font-size: 18px;display: block; ">Make you travelling an ease with CarMania</strong></p>
       <p class="ptext">Carmania gets you the experience you seek in traveling with our luxurious, comfortable and within budget cars. Our fleet has all the cars that you want for your traveling desires.  We know it is not easy for outsiders to navigate smoothly in Bangladesh. Traveling becomes even worst when you don’t have the right vehicle in hand.   Perhaps that is the reason we came up with <strong>Self-drive car rental</strong> options for the travellers. If you love to drive cars but you feel that you won’t get one within your budget when you are on an alien land; we prove you wrong. We get you the cars of your choice that too within a range that is not at all a pain for anyone.</p>

       <p><strong style="font-size: 18px;display: block;">Easy to pick</strong></p>
       <p class="ptext">Once you have talked to our representatives you can easily pick the car you want and there won’t be any tedious or drudging formalities. We understand your condition and always want to make your stay in Dhaka and Bangladesh comfortable and time effective. Talk to us and we hand you the keys of the cars.</p>

       <p><strong style="font-size: 18px;display: block;">Variety in packages</strong></p>
       <p class="ptext">We don’t limit your traveling aspirations. You can simply go for any of the packages we have and the car is yours. Whether you want car for an hour, a few hours or an entire day or more; we have that perfect package for you.   Our car rental packages make us the best rental services in the vicinity.  The best thing is Carmania covers all the options that a traveller might want to opt for. Once you have taken our <strong>self-drive cars in Dhaka</strong> you will not have to rely on anyone. Don’t take favours unnecessary when we get you the cars on the go!

        So, we don’t tell you to blindly trust us. Go ahead, take our services, experience and then keep a verdict! We are sure that our cars won’t disappoint you!</p>

       <div class="ptext"style="border-bottom:solid windowtext 1.0pt; padding: 0in 0in 1.0pt 0in ;">
    
        <p style="text-align: justify">&nbsp;</p>
    </div>

       <p><strong style="font-size: 18px;display: block;">Description</strong></p>
       <ul>
           <li class="ptext" style="text-align: justify">Enjoy traveling with selfdrive car rental.  Our selfdrive cars in Dhaka will get you to your spots in Bangladesh with a smile on your face. Rule the roads with us!</li>
           <li class="ptext" style="text-align: justify">Make traveling a boon with selfdrive car rental. Once opted for self-drive cars in Dhaka, you won’t regret it. Stay ahead of other tourists with best cars in your hand.
        </li>
</ul>

   <p><strong style="font-size: 18px;display: block; ">Meta description for social networking sites</strong></p>
   <p class="ptext">Save your day with our self-drive car rental. Once you tried self-drive cars in Dhaka, the roads will call you for exploration. Siting tours or important visits; make it happen with our car rentals for you.</p>
   <p style="text-align: justify">&nbsp;</p>


   <p><strong style="font-size: 18px;display: block;">Catchy line</strong></p>
   <p class="ptext">Fall in love with Bangladesh with our self-drive car rental Facilities. Indeed, once self-drive cars in Dhaka are in your hand; you are going to be enchanted for sure.</p>

</div>
<div class="side_image">
  <img  src="../static/blog/images/car3.jpg">
</div>
</div>



</section>
<div class="footer">
   
        <a style="font-size: 30px;" href="{% url 'blog:home_page' %}">CARMANIA</a>
        <p> Hotline: +88 096 629 712<br>
            WhatsApp: +88 01622 629 712<br>
            Email: contact@carmania.com.bd
          </p>
    
</div>
{% endblock %}

blog/templates/blog/sell_car_post_detail.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block body %}
<div class="jumbotron">
    <!-- <img style="border-radius: 50%;width:60px;height:60px;" src="{{ user.user_profile.image.url }}"> -->
    <h1>{{ object.author }}</h1>
      <hr>
    <p>Car Name : {{ object.car_name }}</a></p>
    <p>Engine Capacity  : {{ object.engine_capacity }}</a></p>
    <p>Model : {{ object.model }}</a></p>
    <p>Color : {{ object.color }}</a></p>
    <p>Seat Capacity : {{ object.seat_capacity }}</a></p>
    <p>Price : {{ object.price }}</a></p>
    <p><img style="width:300px;height:200px;" src="{{ object.image.url }}"></p>
</div>
{% endblock %}

blog/templates/blog/takerent_list.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block body %}
<style>
	.jumbotron{
		background: url(../static/blog/images/pic1.jpg);
		background-size: cover;
		margin-bottom: auto;
		height: 1500px;
		background-attachment: fixed;
		color: white;
		align-items: center;
	}

	

		.content-table{

           border-collapse: separate;
           margin: 30px 150px 10px;
           font-size: 20px;
           width: 58%;

        }
        .content-table thead tr{

            color: cadetblue;
            text-align: left;
            border-spacing: 30px;
        }
	/*.type_car{
		display: flex;
		
		
	}*/
	/*.type_name{
		display: flex;
	}*/
	/*.type{
		margin-top: 79px;
    	margin-left: 300px;
	}
*//*
	.type_name p{
		margin-left: 130px;
	}*/


</style>

<div class="jumbotron">
		<h1 style="text-align: center; margin-top:-30px">Choose your desire car</h1>  


		<table class="content-table">
  			<thead>
    			<th>Pictures</th>
    			<th>Info</th>

			</thead>
  			{% for value2 in post %}
 			 <tr>
    			<td><img style="width:300px; height:200px;" src="{{ value2.image.url }}"></td>
    			<td style="list-style-type: none;">
    				<li style="color: white" >Car Name : <a href="{% url 'blog:detail1' pk=value2.pk %}">{{ value2.car_name }}</a></li>
         			<!-- <li style="color: white" >Contact Number : {{ value3.contact }}</li>
         			<li style="color: white" >Client Name : {{ value3.client }}</li>
       				<li style="color: white" >Description : {{ value3.description }}</td></li> -->


  			</tr>
  			{% endfor %}
			</table>
</div>
{% endblock %}